# Generated by Django 2.2 on 2019-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github', models.URLField()),
                ('url', models.URLField()),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('lastModified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('lastModified',),
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('associatedLanguage', models.CharField(blank=True, choices=[('PY', 'Python'), ('CPP', 'C++'), ('C', 'C'), ('JS', 'JavaScript'), ('TS', 'TypeScript'), ('HTML', 'HTML'), ('CSS', 'CSS')], default='PY', max_length=4)),
                ('general', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='PorjectModel',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='projects.Skills'),
        ),
    ]
